output_example = """
{
    "title": "{title of the question}",
    "question_id": "{question id}",
    "response": {
        "answer": "{student's answer to the question}",
        "response_id": "{response id}",
        "feedback": "{feedback generated by you on the student's answer}",
        "type": "{type of response, can be: correct, partially correct, incorrect}",
        "wrong_snippets": ["{sections of the answer marked as wrong}"]
    }
}
"""

input_example = """
{
    "title": "{title of the question}",
    "question_id": "{question id}",
    "response": {
        "answer": "{student's answer to the question}",
        "email": "{student's email}",
        "response_id": "{response id}",
    },
    "language": "{language of the response}"

}
"""