output_example = """
{
    "title": "{title of the question}",
    "question_id": "{question id}",
    "response": {
        "answer": "{student's answer to the question}",
        "response_id": "{response id}",
        "feedback": "{feedback generated by you on the student's answer}",
        "type": "{type of response, can be: correct, partially correct, incorrect}",
        "wrong_snippets": ["{sections of the answer marked as wrong}"]
    }
}
"""

input_example = """
{
    "title": "{title of the question}",
    "question_id": "{question id}",
    "response": {
        "answer": "{student's answer to the question}",
        "response_id": "{response id}",
    },
    "feedbackList": [list of feedbacks]
    "language": "{language of the response}"
}
"""

rule_example = """
Input:
    {
        "title": "What is the basic process of photosynthesis in plants?",
        "question_id": "123123",
        "response": {
            "answer": "Photosynthesis is the process by which plants, using solar energy, convert carbon dioxide and oxygen into glucose and water.",
            "response_id": "123123-12",
        },
        "language": "English"
    }
Output:
    {
        "title": "What is the basic process of photosynthesis in plants?",
        "question_id": "123123",
        "response": {
            "answer": "Photosynthesis is the process by which plants, using solar energy, convert carbon dioxide and oxygen into glucose and water.",
            "response_id": "123123-12",
            "feedback": "Your response has a basic understanding of photosynthesis, but there is a small misconception in how you described the process. In photosynthesis, plants use carbon dioxide (CO2) and water (H2O) to produce glucose (C6H12O6) and release oxygen (O2) as a byproduct. You reversed the products and reactants in your response. Make sure to review this part to ensure accuracy in describing the process.",
            "type": "partially correct",
            "wrong_snippets": ["convert carbon dioxide and oxygen into glucose and water"]
        }
    }

"""